projects:
  skillShowcaseApi:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src\app\API.service.ts
        docsFilePath: src\graphql
        graphQLApiId: qa7qru2a6beivnws3e7tvyrhe4
      endpoints:
        prod: >-
          https://47wjbccd25f7roljbz73r3uyj4.appsync-api.us-east-1.amazonaws.com/graphql
