// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9699d357-ff6c-41de-983c-60019acc398e",
    "aws_cognito_region": "us-east-1",
    "aws_mobile_analytics_app_id": "3264c5c6e71644418092883344d93f5d",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_content_delivery_bucket": "skillshowcase--hosting-bucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://skillshowcase--hosting-bucket.s3-website-us-east-1.amazonaws.com",
    "aws_appsync_graphqlEndpoint": "https://47wjbccd25f7roljbz73r3uyj4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-sxqp4ckcqnairejt7qigoru5ua"
};


export default awsmobile;
