// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9699d357-ff6c-41de-983c-60019acc398e",
    "aws_cognito_region": "us-east-1",
    "aws_mobile_analytics_app_id": "3264c5c6e71644418092883344d93f5d",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_content_delivery_bucket": "skillshowcase--hosting-bucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://skillshowcase--hosting-bucket.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
